; PlatformIO Project Configuration File
; Kelompok 14 - Smoke Detector Prototype
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; Target: ESP32 (AZ-Delivery DevKit v4)
; Framework: Arduino
; For more information: https://docs.platformio.org/page/projectconf.html

[env:az-delivery-devkit-v4]
; ESP32 development board configuration
platform = espressif32
board = az-delivery-devkit-v4
framework = arduino
monitor_speed = 115200  ; Serial monitor baud rate
lib_deps = bblanchon/ArduinoJson@^7.4.2  ; JSON serialization library
board_build.filesystem = littlefs  ; Embedded filesystem for web interface
